#!/bin/sh
PID_FILE=/var/run/openvpnd.pid
CMD="none"
. /etc/openvpnd/openvpnd.conf
SELECTED_SERVER=""

for arg in $@
do
	case "$arg" in 
		start)
			CMD="start"
			;;
		stop)
			CMD="stop"
			;;
		restart)
			CMD="restart"
			;;
		status)
			CMD="status"
			;;
		*)
			echo "Invalid argument! Usage: $0 {start|stop|restart}"
			exit 1
	esac
done

[ "$CMD" = "none" ] && echo "Wrong initialization! Usage: start_vpn {start|restart|stop}" && exit 1

set_selected_server() {
	COUNT=0
	SERVERS=$(ls $SERVERS_FOLDER/us*)
	for SERVER in $SERVERS; do
		COUNT=$((COUNT+1))
	done
	IND=$(shuf -i 1-$COUNT -n 1)
	CURR_INDEX=0
	for SERVER in $SERVERS; do
		CURR_INDEX=$((CURR_INDEX+1))
		[ "$CURR_INDEX" = "$IND" ] && SELECTED_SERVER=$SERVER
	done
}

run_post_start_scripts() {
	for SCR in $(ls $POST_START_SCRIPTS_FOLDER)
	do
		sh "$POST_START_SCRIPTS_FOLDER/$SCR"
	done
}

run_post_stop_scripts() {
	for SCR in $(ls $POST_STOP_SCRIPTS_FOLDER)
	do
		sh "$POST_STOP_SCRIPTS_FOLDER/$SCR"
	done
}

start_daemon() {
	echo "Starting openvpn..."
	[ -f "$PID_FILE" ] && PID=$(cat $PID_FILE) || PID=""
	[ ! "$PID" = "" ] && echo "Already running!" && exit 1
	echo "Initializing VPN..."
	set_selected_server
	echo "Server: $SELECTED_SERVER"
	openvpn --config "$SELECTED_SERVER" --auth-user-pass /etc/openvpn/auth.txt 2>&1 > /dev/null &
	PID=$(echo $!)
	touch $PID_FILE && echo "$PID" > $PID_FILE
	[ -d "$POST_START_SCRIPTS_FOLDER" ] && run_post_start_scripts
	echo "OpenVPN started."
}

stop_daemon() {
	echo "Stoping openvpn..."
	PID=$(cat $PID_FILE)
	[ "$PID" = "" ] && echo "Not running!" && exit 1
	kill -9 $PID
	rm $PID_FILE
	[ -d "$POST_STOP_SCRIPTS_FOLDER" ] && run_post_stop_scripts
	echo "OpenVPN stoped."
}

daemon_status() {
	[ -f $PID_FILE ] && PID=$(cat $PID_FILE) || PID="" 
	[ "$PID" = "" ] && echo "OpenVPN Daemon Not running" || echo "OpenVPN Already Started; pid=$PID"
}

case "$CMD" in
	start)
		start_daemon
		;;
	stop)
		stop_daemon
		;;
	restart)
		stop_daemon
		start_daemon
		;;
	status)
		daemon_status
		;;
	*)
		echo ":)"
esac

exit 0
